name: hugo build to gh-pages
on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.HUGO_BUILD }}
          publish_dir: ./docs
          cname: kiumars.tk

      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.2
        env:
          key: main
          branches: gh-pages
          files: favicon.png
          
      # - name: CopyFavicon
      #   uses: actions/checkout@v2
      #   env:
      #     SRC_FOLDER_PATH: 'main'
      #     TARGET_BRANCH: 'gh-pages'
      #   run: git config --global user.name 'GitHub Action' &&\
      #       git config --global user.email 'action@github.com' && git fetch &&\
      #       git checkout $TARGET_BRANCH &&\
      #       git checkout ${GITHUB_REF##*/} -- favicon.png &&\
      #       git add -A &&\
      #       git diff-index --quiet HEAD ||  git commit -am "deploy favicon" &&\
      #       git push origin $TARGET_BRANCH